### ISSUE TITLE
A question and a suggestion 

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#1]
Would you think about the Alchemical Paper/reusable paper system discussed in the thaumcraft suggustions thread

And maybe the paper recipie from the same issue could drop 2 paper with paper as the catalyst.

**Comment by enderger** [comment]
And in metal transmutation, it says even tough instead of even though

**Comment by Frontrider** [comment]
You read through it pretty fast xD. My English is good, but it's still not my native language, I'm doomed to make small mistakes here and there.

I'll write up some guidelines if required, but as a general rule of thumb, try keeping one topic in one issue. That really helps the developer to figure out what is going on.

**Comment by Frontrider** [comment]
That is not what I meant. What I meant is that it should have been 2 issues, since these are 2 separate topics ;)

**Comment by enderger** [comment]
K, I’ll remember that next time...

I will move the comments regarding the lang file to the pull request for the lang file.

**Comment by enderger** [comment]
Or rather copy paste them

**Comment by Frontrider** [comment]
Don't bother for this one. mark it for future reference, as I said, it helps the developer to keep the issues more organized.

**Comment by enderger** [comment]
Can you pause for a moment for me to perform my fixes to the lang?

**Comment by Frontrider** [comment]
it's 11 pm here, so I'm done for today. Go on ahead. You can also make separate requests if you think that some of the lore text should be changed, just keep them separate so I can choose the ones I like. sounds bad, but it's actually less work that way.

**Comment by Frontrider** [comment]
And you can do whatever you want, git covers it anyways.
