### ISSUE TITLE
Release locations

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#10]
As you are nearing the release stage, I would like to recommend to release to the curseforge mod catalog(as well as other platforms, if you had any in mind). My reasoning here is that their modpack database usually allows only mods released on the platform to be included within them. I personally release custom modpacks there and would honestly like to include this in my modpacks going forward.

**Comment by Frontrider** [comment]
I'll push it to curse forge. nowhere else There's no other place to download mods from unless:
 * you want to risk malware
 * you don't want to support mod authors
 * you want to support piracy

I will also try to sign the jar to help to protect it against tampering.

**Comment by enderger** [comment]
K, I just was making sure.
