### ISSUE TITLE
Thaumcraft api on GitHub causes mod compilation to fail

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#11]
When I made my JAR file, I encountered an issue with the thaumcraft api files, the thaumcraftapi.java file to be precise. The comments that Azanor left in the file are shifted onto new lines and loose their status as comments. I believe that copying the contents of the current thaumcraftapi class into the class in the repository could fix this issue.

**Comment by Frontrider** [comment]
I found the issue, the API is encoded to work only on windows (the line endings are wrong), I'll run a converter on it, and it'll be fine.

**Comment by Frontrider** [comment]
*when I get there, hopefully tomorrow.

**Comment by enderger** [comment]
It seems isolated to the one class

**Comment by Frontrider** [comment]
I think I saw more. I'll look into it.

**Comment by enderger** [comment]
It did not error when I compiled the jar on Linux on any file other than the api. I remember that one of the golem-related files was missing when I compiled the jar.

**Comment by Frontrider** [comment]
Yeah, first I got the API from the repo, and it was missing.

**Comment by Frontrider** [comment]
Found the issue, I ran a code formatter on it before committing, and it broke the api.

**Comment by enderger** [comment]
Is this fixed?

**Comment by Frontrider** [comment]
Supposedly. It was messing up the javadoc comments for some reason. Probably the encoding.

**Comment by Frontrider** [comment]
Yes, as long as no formatters are run on those files.
