### ISSUE TITLE
No visual way of knowing if the creature enchantment worked

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#12]
Just what it says on the tin. It seems fairly hard to tell if your creature enchantment worked in creative mode.

**Comment by Frontrider** [comment]
I know about that, I'll figure something out.
I don't really know how to work with entities directly (I currently only use capabilities to attach behaviour), so I don't know how to render on them, and I have no time to learn it now.

**Comment by Frontrider** [comment]
(accidentally hit enter)

That is one reason I decided to go this route, so I need not to create an entity yet.
I might just add a prefix/postfix to the name of the creature.

**Comment by Frontrider** [comment]
Although, I'm not putting it to a priority, since mechanically it works.

**Comment by enderger** [comment]
Particle effect when applied would work

**Comment by Frontrider** [comment]
Currently thinking about showing some icons when you look at it wearing the goggles. (those can also be reused to display what you have on you)

But, particles are probably the better option.

**Comment by Frontrider** [comment]
Feel free to.

**Comment by enderger** [comment]
https://drive.google.com/open?id=1QQUcQNPt5-_vXGFk3dHnBo0EHQ1o9WTf

**Comment by Frontrider** [comment]
With particles, I'd think that it would be better, if the particle was representing the enchantment, and the color of it represented the level of it.

**Comment by Frontrider** [comment]
That is literally all the information you need.

**Comment by enderger** [comment]
I have made a particle texture, just needs to be coded into the game. From what I know of the grass texture, some colors can be programmed with it into the individual enchantments.

**Comment by Frontrider** [comment]
What I meant:
- the texture of the particle could represent the the  enchantment type (protection, fertile, etc)
- the color of the particle could represent the level (1,2,3...)

When we only work with colors, we would make it unreasonably hard to distinguish, and develop the enchants. I'll make some mock-ups when I get there.
It would quickly reach the point (it might have already reached that) where there are no distinct colors left.

**Comment by enderger** [comment]
Ok, I'll make a collection of particles and color code them
And don't think for a second that I don't use rgba for my colors, I can make loads. I'll use gradient for the levels and distinct colors for the particles. That will net us many more particles.

**Comment by enderger** [comment]
I'll make individual textures for each

**Comment by enderger** [comment]
First particle set has finished. The strength particles as well as all other textures that I make, will be available at http://bit.ly/TArcana

**Comment by Frontrider** [comment]
I'd like to color the texture myself, than I could scale it for whatever level I want to make by default.
I have made 3 different "upgrade items" for each tier, and coloring the particle according to that is the way to go.
I'll push them today when I get there.

**Comment by enderger** [comment]
I have uploaded a set of particles that represent the effects of the enchantments, ready for color

**Comment by Frontrider** [comment]
Ok, I'll look at them when I get home.
I want to see if I can make it so that no particles show up on the enchanted player's side. It's not really bothersome for others, but can be bothersome for the player. If I can do that, than I think I'll display the particles as icons above the toolbar, bellow the enchantment bar.

**Comment by Frontrider** [comment]
![particles](https://user-images.githubusercontent.com/6755034/43734131-10f48012-99b7-11e8-9879-f9468c6d68c7.jpg)

**Comment by Frontrider** [comment]
Although, on a second look adding a new particle isn't that easy.

**Comment by enderger** [comment]
A vanilla particle that displays when the book is used may give some visual feedback.

**Comment by Frontrider** [comment]
Particles are harder (at least work differently from the rest). But I think that now I have a lead.

**Comment by Frontrider** [comment]
Got the concept. I will display a circle bellow the entity, that contains the following information:
- what enhantments are applied (enchant icon will display)
- what level enchants applied (the color of the enchant icon)
- (an idea that I'm toying with) how acclimated you are to the enchantment. You can't use it properly, or without risk if you're body isn't used to it.

This circle should also display for the player in first person, so he knows what's on him.

**Comment by Frontrider** [comment]
May also add an enchantment that hides this display. (Should be removeable), or maybe temporary.

**Comment by Frontrider** [comment]
iteration 1: now it's possible to tell.
![2018-08-08_21 40 13](https://user-images.githubusercontent.com/6755034/43861063-fc87e9ca-9b55-11e8-86c2-ec6d47f383f9.png)

**Comment by enderger** [comment]
What about, rather than making it visible with an enchantment that hides it, adding a recipe to upgrade the goggles of revealing that lets you see the above particles.

**Comment by Frontrider** [comment]
If I do that, than I'd rather have the googles do that by default. 

And the goal of hiding it would be to gain advantage in a pvp situation. And it's also just the base, there's a few other details I want to add to it. Although, I do have an idea to turn off the entire thing, which will make sense after your body will have to get used to it (or suffer the consequences).

**Comment by Frontrider** [comment]
I might also render it in first person, so it can serve as the indicator for what's on you.

**Comment by enderger** [comment]
I find that hiding it could be mainly used for unobtrusiveness and lag, as rendering particles sometimes is laggy.

**Comment by Frontrider** [comment]
Currently, I don't use particles, (it's a flat textured sheet I render bellow the player) and at least for the first release I won't use any particles. I have some plans, but than I'll put in a setting to turn it off.

**Comment by Frontrider** [comment]
The rendering is closer to grass, than a portal.

**Comment by Frontrider** [comment]
Altough, it might be cool to do the thing that thaumcraft did with the nodes: make it faint.

**Comment by Frontrider** [comment]
The prototype implementation, that shows the enchant as well. (intended to be a hearth, but looks like a chest-plate)

![enchant](https://user-images.githubusercontent.com/6755034/43991149-a49b09a0-9d66-11e8-8747-49528523da3e.gif)

**Comment by Frontrider** [comment]
I'm finding that I still build some of the infrastructure around it. (proper storage, syncing, the implementation for the enchant itself, etc) so, for now the only thing I do on this one, is recolor the small icon to make it represent it's level.

I know what I'll do in terms of hiding tough.

**Comment by Frontrider** [comment]
![enchant_v2](https://user-images.githubusercontent.com/6755034/43994501-49b3447a-9d9e-11e8-9bd9-7a4173a82783.gif)

**Comment by Frontrider** [comment]
The indicator is functionally ready.

**Comment by Frontrider** [comment]
And now we'll have the reason why I renamed it to 0.1.0:
I'm going to close this, and call it "working". The rendering is buggy, but I'm not going to delay that feature anymore.
It is a visual way of telling that it's working. I'll want experience and feedback on the actual obtrusiveness of it (screenshots, and detailed descriptions)
