### ISSUE TITLE
Proper icon

### ISSUE THREAD

**Issue by Frontrider** [Frontrider/thaumic_arcana#15]
I will release it with the current placeholder (which may or may not be re-used for the entry of the player related things), but the research tab still needs a proper icon.

**Comment by enderger** [comment]
I have made a possible design: https://drive.google.com/open?id=1gfR0nJAPPSVbLDXmaCfS48OPfgITmgi4

**Comment by enderger** [comment]
It is 32 bit, making it compatible with minecraft

**Comment by Frontrider** [comment]
I can't look at it properly now.

**Comment by Frontrider** [comment]
The current concept is this image:
https://en.m.wikipedia.org/wiki/Vitruvian_Man

**Comment by BobbyKilkins** [comment]
I think that would be a good idea

**Comment by enderger** [comment]
The problem is that human beings are difficult to make, especially at a resolution of at maximum 32*32 pixels.

**Comment by Frontrider** [comment]
I do see a lot of 32x32 human sprites, that are more detailed than what I think I need.

**Comment by Frontrider** [comment]
I have a placeholder in it, we'll get back to it later.

**Comment by BobbyKilkins** [comment]
How about a brain? Like a high-resolution Zombie Brain?

**Comment by Frontrider** [comment]
At some point I was thinking about just using the zombie brain item.

**Comment by Frontrider** [comment]
replaced it with the zombie brain, gonna call it a good icon until like 1.0.0.

**Comment by Frontrider** [comment]
I messed it up (now it's missing) but I managed to do enough to say hat I'm releasing it anyways.

**Comment by Frontrider** [comment]
I have one that I'm gonnanbe happy with for now.
