### ISSUE TITLE
0.1.0

### ISSUE THREAD

**Issue by Frontrider** [Frontrider/thaumic_arcana#18]
Now with the unexpected refactor, I'm expecting to update today or tomorrow, than curseforge takes a look at it. (to see that it's indeed not malware)

https://minecraft.curseforge.com/projects/thaumic-arcana

**Comment by enderger** [comment]
Once everything is released, I’ll update my fork and re-spellcheck the lang for 0.1.1, since I would like to help keep the mod as good as possible, and doing it on the minor update’s first bugfix release will make it not take hours to check over(even now, the lang file is lengthy and will grow considerably as more is added to the mod), as I will be able to skim the parts that I have checked already. Besides, I still am waiting for an excuse to fix one error that I missed.

**Comment by Frontrider** [comment]
Well, I guess you already did something to the mechanics: I did made an another powder after all.
![2018-08-12_19 00 39](https://user-images.githubusercontent.com/6755034/44004426-dadc7628-9e62-11e8-907e-fc819f819b5d.png)

There are definitely some inconsistencies/bugs, I'll make a list of what i know about.

The lang file and the research json definitely needs some cleanup (also awaiting suggestions there)

**Comment by Frontrider** [comment]
I have some trouble with the build (been going for more than an hour). Looking into possible solutions.

**Comment by enderger** [comment]
Ill make a jar and send it to you

I have beefy hardware, so it may fix the issue

**Comment by enderger** [comment]
The api is still broke in the project

**Comment by Frontrider** [comment]
I'm moving on to CI-CD (Contious integration and deployment), and check your branch. 0.1.0 is being merged into main right now.

**Comment by wamc2017** [comment]
The 0.1.0-release branch compiles fine for me if makeObfSourceJar is set to false in the build.gradle and the modid is added to gradle.properties, maybe that helps with your issues. :)

**Comment by Frontrider** [comment]
branch merged. and no, it's just taking a while to do the obfuscation steps..

**Comment by Frontrider** [comment]
Doing CI-CD setup right now, in the meantime, you can hook me up with jar until I get it ready. I'm so exited.

Pushing the changelog, than it should be deployed to curseforge.

**Comment by Frontrider** [comment]
my goodness, the CI build is actually showing up for merge requests.

**Comment by Frontrider** [comment]
We'll see it tomorrow, I might have some issues in my buildscript.

**Comment by enderger** [comment]
Anyhow, just found an issue in the build.gradle. will add to the spellcheck pull request

**Comment by enderger** [comment]
I have compiled a jar for release and made a functional build.gradle(for my custom jar, I removed cursegradle, but left it in for the version in the pull request).

**Comment by enderger** [comment]
As for the obfuscation steps taking a while, I think that they are broke, as I am experiencing freezes on the exact same step. Debug input freezes, making me think that an error is causing a failure. Compiling from command line.

**Comment by enderger** [comment]
The file that I made works, just does not use cursegradle. Anyways, the created jar comes as modid1.0.jar in the original script. Fixed in my buildfile.

**Comment by enderger** [comment]
The same thing happened when compiling my earlier jar.

**Comment by Frontrider** [comment]
I'll do it when I get there.

**Comment by Frontrider** [comment]
published, and I'm going to be busy the next few days.

**Comment by Frontrider** [comment]
Now that the jar is out, I'm closing it.
