### ISSUE TITLE
Better Stabilizers 

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#19]
While you probably already know this, thaumcraft stabilization is severely limited. As far as I know, to get maximum stability out of the infusion altar, you can only use 12(in total) skulls, candles, and the like, as well as 4 infusion stabilizers. This usually only covers up to moderate instability, which simply is not enough to handle dangerous instability levels. I think that a solution to this could be some sort of turning device(biothaumiturgical, of course) that lets you point stabilizers like heads.

**Comment by enderger** [comment]
The problem lies in the fact that it is borderline impossible to stabilize the altar to a point where infusion at a level higher than the high level is even possible with creative mode.

**Comment by Frontrider** [comment]
Well, I was able to do it once, I'll check back when I can.

**Comment by Frontrider** [comment]
Looking at the API, the only thing I could do is adding a new stabilizer.

**Comment by Frontrider** [comment]
After that, I think I'm going to close it since I can't really do anything about it.
