### ISSUE TITLE
formula crafting

### ISSUE THREAD

**Issue by Frontrider** [Frontrider/thaumic_arcana#24]
0.1.0 implements a different way of alchemy, involving a special mixture of salis mundus and a variety of essentia. This is a stabilized but weaker mixture (it won't set your hair on fire), what you should think of as a paste.

The current crafting mechanic is that you apply it to items on the Experiment Table.
It also supports partial consumption (up to 16 uses), but I still did not manage to get it to not to work in the alchemy recipes.

I'd like to hear some ideas on what it could be used for.

**Comment by enderger** [comment]
Magical glue bottles that are reusable? Would do away with overpriced slime farms on servers.

**Comment by enderger** [comment]
Maybe a recipe for void seeds(so we don’t have to blow rifts)?

**Comment by Frontrider** [comment]
I have an idea for that. But when I get to do that, it'll be at least 0.2.0.

**Comment by enderger** [comment]
I think that the recipe being reusable would be nice.

**Comment by Frontrider** [comment]
For this thread: Throw out whatever you can think of. There is certainly value in any ideas that are in this thread.

**Comment by Frontrider** [comment]
https://github.com/Frontrider/thaumic_arcana/projects/6#card-12225014

**Comment by Frontrider** [comment]
https://github.com/Frontrider/thaumic_arcana/projects/6#card-12225014

**Comment by Frontrider** [comment]
Starting to understand it more. It will be done via in world crafting, and the closest thing I could think of is the Mutandis from witchery. Whitout the complete randomness.

Slime will probably be crafted from a block of flesh.

**Comment by Frontrider** [comment]
It might actually become a burden, I'll leave it in until 1.0

**Comment by Frontrider** [comment]
Really keen on removingit altogether. No longer required and is becoming a burden.

**Comment by Frontrider** [comment]
Removed from dev, closing.
