### ISSUE TITLE
Crash on opening infusion chapter with ctm installed

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#26]
When I open the infusion chapter in the thaumonomicon with CTM installed, I get a crash. 

Report: https://gist.github.com/enderger/5e1718d1f1ae459e740135b405dc1b0f

**Comment by enderger** [comment]
It only occurs when Thaumic Arcana and CTM are installed.

**Comment by Frontrider** [comment]
Can you check it with thaumcraft+ctm only, than slowly add the other mods back? I do nothing in the infusion chapter.
Also, does it occur every time, or just sometimes?

I'll have to ask around.

**Comment by enderger** [comment]
Every time, and it seems to be a conflict between CTM and Thaumic Arcana, as no other mod is installed when I reported the bug

**Comment by wamc2017** [comment]
That's a bug with ctm and was fixed some versions ago, update to 0.3.2.18 and it should be fixed... (you're using 0.2.3.12)

**Comment by enderger** [comment]
Odd, as it seems to only occur with both Thaumic Arcana and ctm installed, with other addons not causing the issue.

**Comment by wamc2017** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63

As you see in this issue, that happens with several different mods, it's not exclusive to Thaumic Arcana...

**Comment by Frontrider** [comment]
Haven't got there to investigate. What I was thinking from the crash report, is that CTM is crashing thaumcraft (especially, since I have no content on that page). Thanks, @wamc2017.

Closing.

**Comment by enderger** [comment]
The reason that I report here is that it does not happen without Thaumic Arcana

**Comment by Frontrider** [comment]
Still not releated to me. I don't do anything that would replace thaumcraft blocks.
