### ISSUE TITLE
Chapter appears without plants research, but has no content

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#27]
The chapter ITSELF is shown when I give myself the biothaumic mind research without getting the plants research, but it is empty until you get the plants research. Content appears as intended when you get the plants research, so it seems to be that the chapter remains locked only for the biothaumic mind, with the research working as intended.

**Comment by Frontrider** [comment]
The research text shouls note, that it's the biothaumic mind, that inspires you to dvell deeper into the living.

If not, than we have a problem.

**Comment by Frontrider** [comment]
I solved some of the issues I had, I will try to get 0.1.1 out this weekend. No promises.

**Comment by enderger** [comment]
I'll get a screenshot of the research

**Comment by Frontrider** [comment]
Same as #29, listed in the changelog as a known issue.

**Comment by enderger** [comment]
The research itself does not render, different bug

**Comment by Frontrider** [comment]
The lang key is empty.

**Comment by Frontrider** [comment]
It renders an empty string.
