### ISSUE TITLE
Crash with Fleshing it Out Research

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#28]
BEFORE completing it, Fleshing it Out crashes the game when you open the research. The crash is very similar to #25's, so they may be related. I'll report back when I find the culprit.

**Comment by Frontrider** [comment]
Give me a crash report, might be the same typo. I'm currently figuring out a technique to test my jsons, so it won't happen again.

**Comment by enderger** [comment]
Item NBT: {Aspects:[{amount:10,key:"beastia"}]} is the culprit! Spelled bestia in the api.

**Comment by Frontrider** [comment]
what I expected.

**Comment by enderger** [comment]
Fixing my jar for testing.

**Comment by enderger** [comment]
Just copy-pasting from aspects.java in the api.

**Comment by Frontrider** [comment]
Writing the automatic test for it, so it is caught before it gets out to the public.

**Comment by Frontrider** [comment]
Test written, caught all of the errors, closing.

**Comment by Frontrider** [comment]
https://github.com/Frontrider/thaumic_arcana/blob/0.1.1/src/test/java/hu/frontrider/arcana/ResearchTester.java

**Comment by Frontrider** [comment]
https://app.codeship.com/projects/301567/builds/36451261?pipeline=ff529967-04c7-4944-85c0-94694e361423

This result includes this issue.
