### ISSUE TITLE
Missing language key

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#29]
thaumic_arcana.wheat.stage.5 is missing in the lang file, causing a malfunctional research. Either that or it is marked as thaumic_arcana.wheat.stage.6.

**Comment by enderger** [comment]
Make that 2! The advanced creature enchanter research also is missing stage 3's text

**Comment by Frontrider** [comment]
Fixed, will push before the weekend, so you can take a look. Trying to save up on my builds for now, than we'll see where it goes. (When I push, the ci server will run all the tests, and use a build)

**Comment by enderger** [comment]
In aspects.java, the bottom of the file contains an exhaustive list of all Thaumcraft aspects.

**Comment by Frontrider** [comment]
It would be nearly impossible to use the API whitout that, and I challange you to look up ll the places where an aspect is, and check the amount of time it takes, to copy and paste them one by one.
Also, just look through the code and check where I reference those fields.

As I said, I wrote a test, that checks if the aspects are indeed valid.

**Comment by enderger** [comment]
There is a copy of every aspects initialization code at the bottom of aspects.java.

**Comment by Frontrider** [comment]
That is not a copy. That is the initialization code.

**Comment by Frontrider** [comment]
What I said is: I can prototype faster by not checking back and forth between several files. 
The problem will be solved by the automatic tests, that will fail, if something is not correct.
