### ISSUE TITLE
No way of enchanting the creature enchanter

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#30]

**Comment by Frontrider** [comment]
Read the research.

**Comment by Frontrider** [comment]
That feature also has some unit tests, that are passing.

**Comment by enderger** [comment]
That gives me a blank enchanter, cant enchant it with anything. If I’m incorrect, then I can’t figure it out.

**Comment by enderger** [comment]
I can only get as far as the powder

**Comment by Frontrider** [comment]
Thanks for the feedback, I need to find  better way to signal what I mean by "apply"/"application". Right click the dust with the book in your offhand, on the enchanting table.
I'll need a fake recipe to show it.

Added a new entry to the experiment table, describing that you can do the same kind of crafting with the enchanting table.

**Comment by Frontrider** [comment]
I tought I already had that, sorry.

**Comment by Frontrider** [comment]
And yes, I see how terrible I am at this whole "handle issues" thing, thanks for patience.

**Comment by Frontrider** [comment]
Closing.
