### ISSUE TITLE
The ring from self enchantment is not visible

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#31]
Only applies to self-enchantment in first person.

**Comment by Frontrider** [comment]
Yeah, that is not there yet.

**Comment by enderger** [comment]
So far so good. Seems to be ok at the moment.

**Comment by Frontrider** [comment]
It might get a bit "thicker" (the small icons are elevated above the circle), but the size will not change.

**Comment by enderger** [comment]
Maybe holding sneak should hide all renders, making it an advantage AND a disadvantage.
