### ISSUE TITLE
[1.12.2] [0.1.0] Crash with Better with Mods

### ISSUE THREAD

**Issue by wamc2017** [Frontrider/thaumic_arcana#32]
Hi,

the game crashes at startup if Thaumic Arcana is installed alongside Better with Mods.

Crash-Report: https://gist.github.com/wamc2017/29e71e2d0e6313c64ab8d2a2cf7a5213

If this is an issue, which needs to be solved at BWMs side, I will report it to them. (I guess there's some Nullcheck missing in Formula.java)

Mods used to test this issue (no other mods installed):
forge: 14.23.4.2749
baubles: 1.5.2 
thaumcraft: 6.1.BETA22 
bwm: 2.3.8
jei: 4.12.0.215 
thaumic_arcana: 0.1.0

Thanks for looking into it. :)
Best regards,
wamc

**Comment by Frontrider** [comment]
It looks like he's calling one of my methods, before I'm fully initialised. I know how to fix it.
I'll get the fix out this weekend.

**Comment by Frontrider** [comment]
Thanks for the catch, the plant ball had the same issue.

**Comment by Frontrider** [comment]
Also noting it on their side, since it might break again in the future.
