### ISSUE TITLE
A way to get void seeds

### ISSUE THREAD

**Issue by Frontrider** [Frontrider/thaumic_arcana#33]
from: #24

**Comment by wamc2017** [comment]
The rifts are a base thaumcraft feature to gate the void seeds and if you add some easier way to get them, nobody would use the TC way, if the method to get them is harder, nobody would use the TA way...
Imho an addon shouldn't change base mechanics and if it does it should be configurable (and maybe disabled by default)

**Comment by enderger** [comment]
It could be a harder but automatable way, so you can automate them but need to use this way.

**Comment by wamc2017** [comment]
The void syphon automatically extracts void seeds from the rifts, is that not enough automation?

**Comment by enderger** [comment]
Autocrafting and rift movement?

**Comment by Frontrider** [comment]
Well, my idea would have been more like:
90+% of the time releases taint, the remaining is either a seed, or a chance for a seed.

**Comment by Frontrider** [comment]
After a while, also kills the thing that produces it.

**Comment by Frontrider** [comment]
I have it in the backlog (from the comments, it looks like I probably should not do it), closing it to not to take up space.
