### ISSUE TITLE
Craftable smile balls

### ISSUE THREAD

**Issue by Frontrider** [Frontrider/thaumic_arcana#34]
from #24 

> @enderger 
> Magical glue bottles that are reusable? Would do away with overpriced slime farms on servers.

**Comment by enderger** [comment]
I may make the code for a version of this idea

**Comment by Frontrider** [comment]
The API is there.
Try copying what I do for the part where I apply the formula to the dust. It should support a lot of things, (even the consumption of the block that you use to craft). If you discover something that it should do but it can't, than open an issue.

 Right now I'm doing some cleanup around my recipes (the formula will now includes victus in the recipe) Trying to do it today or tomorrow.

**Comment by enderger** [comment]
Ill wait for json formula crafting

**Comment by Frontrider** [comment]
Life is in the way right now.

**Comment by Frontrider** [comment]
This will be the format, will also require you to create the research. Because of that, I'm debating weather or not I want to rely on a tool that will put it on the classpath. (Resource loader)

https://gist.github.com/Frontrider/f1a4fa51dc15e986c3f2560ab868cdd8

**Comment by enderger** [comment]
I should be able to branch my fork(just realized that that works) and edit the code from there

**Comment by Frontrider** [comment]
I started to use kotlin, so I don't need to write that much infrastructure.Already shrunk somemof my classes.
Also be aware, that tests currently don't work. (You will get errors)

The Formula recipe loader is what needs to be implemented, the rest should work. The enchanting powders are already using this system, but instead of the json, I just generate the recipes from the enchants.

**Comment by Frontrider** [comment]
And always pull the latest dev, that will be it, I'm done trying to feature branch, no capacity for that.

**Comment by Frontrider** [comment]
Implemented requires resource loader, has the side effect that any mod can can put the correct jsons into their resource folders, and it will work. Won't release it until the weekend, because I also have to add the fake recipe to go with it, to make it show up in the thaumonomicon.
![slimecraft](https://user-images.githubusercontent.com/6755034/45054806-5acc8e80-b08e-11e8-9798-fa1c870768b3.gif)

**Comment by Frontrider** [comment]
Looks like that API is not really there, so I might just salvage the infusion crafting to do it.

**Comment by Frontrider** [comment]
Gets recipes from the asset folders of every mod + a folder in my configs. I could not get it to load otherwise.

Can't figure out how to get the player to understand how the crafting works for sure (salvaging infusion is too confusing).

**Comment by Frontrider** [comment]
@enderger  any ideas?

**Comment by enderger** [comment]
Migrate all recipes to the folder in your configs. This should not only let people edit the recipes easily for modpacks; it would give a working example. Just needs to have explanatory comments.

**Comment by Frontrider** [comment]
Yeah, I'll skip scanning the classpath and just use that folder than.

Any ideas on how to display it in the thaumonomicon?

**Comment by enderger** [comment]
Recycle the alchemy system for the formulas

**Comment by enderger** [comment]
For crafting, you could use somthing of a triangle with the block in front, the needed formula on the left sidr, and an item for some recipes(like a phial for creating a bottled slime item)on the right. In the center is the result.

**Comment by enderger** [comment]
Also, the salis mundus particle effect would add pizazz to the whole craft.

**Comment by Frontrider** [comment]
I don't know how to apply that effect. and there is no public API, so I might need to go a little deeper. (will break in an update)

I already ruled out any solution like that, because it's impossible to add new displays. The one that would be used for that is hard coded for furnace.

**Comment by Frontrider** [comment]
Found the code, the display for the recipes are all hard coded to draw only the vanilla thaumcraft recipe types.

**Comment by Frontrider** [comment]
Seeing at it: I doN't mean the creation of formulas. That is already done in the alchemy system. I mean the recipe what you get when you apply it.

**Comment by enderger** [comment]
JEI integration?

**Comment by Frontrider** [comment]
I'm thinking about that but, I should make sure that it can work with thaumcraft alone.

**Comment by Frontrider** [comment]
All thaumcraft recipes are displayed in the thaumonomicon. Because of that, I can not rely solely on JEI.

**Comment by enderger** [comment]
Feature request?

**Comment by Frontrider** [comment]
Already done.

**Comment by Frontrider** [comment]
Not gonna write a jei plugin right now (adding it to my backlog).

It will show up in the tooltip of the item.

**Comment by enderger** [comment]
The vanilla recipe book!

**Comment by enderger** [comment]
That could be implemented into a second gui in the experiment table, possibly with a formula creation system that won’t overflow like a crucible

**Comment by enderger** [comment]
They have embraced and extended minecraft...
And they are now extinguishing java edition.

**Comment by Frontrider** [comment]
If bedrock actually works as a replacement (which is currently not the case), than why not?

back to topic: formula crafting from json files is added and working. You need to add research via resource loader, than configure my mod to load it.

**Comment by enderger** [comment]
Linux and mac users

**Comment by enderger** [comment]
Not to  quazi connectivity
