### ISSUE TITLE
create "arcane cage" that can trap small animals to be used in experiments.

### ISSUE THREAD

**Issue by Frontrider** [Frontrider/thaumic_arcana#38]
Any ideas?

**Comment by Frontrider** [comment]
Labrats implemented, you can store one in the experiment table. It also requies you to feed it and supply water, or else it dies. (Can be automated)

**Comment by Frontrider** [comment]
thevfluid implementation of forge still isn't the best, gonna ditch that part.

**Comment by Frontrider** [comment]
I made the first models, but I will only upload it to discord, since that's better for it. (you got the notification for the channel). Later I1ll upload them to curseforge when it's fixed.

**Comment by Frontrider** [comment]
I won't add cheese myself, but there is a list in the config that contains the valid food items for them.
List a bunch of items from other mods,and I'll set the defaults.

**Comment by Frontrider** [comment]
The 0.1.2-dev branch contains a file called "configuration.java" (this class is the config file, thaumic_arcana.cfg) that has an array called "rodentFoodList". It contains the names of e items that can be used as bait/food.

Those are the default values, feel free to make a pr, but it should only contain this file, nothing else.

**Comment by Frontrider** [comment]
@enderger will that work for you? :)

**Comment by enderger** [comment]
That will be quite good.

**Comment by Frontrider** [comment]
And it also doesn't matter weather or not the mod is installed, so anything can be added to the default configuration.
