### ISSUE TITLE
[1.12.2] [0.1.1] Research table phial bug

### ISSUE THREAD

**Issue by wamc2017** [Frontrider/thaumic_arcana#42]
Hi,

during researching on the research table, there's a bug with some cards which needs phials to complete. Some of those need a phial with 1x aqua in it, but there's no way to obtain a phial with 1x aqua (only 10x)

![researchtable](https://user-images.githubusercontent.com/33242447/44308413-ac4dfb80-a3b5-11e8-9729-24f8ef0904a9.png)

Mods used to test this issue (no other mods installed):
Forge:  14.23.4.2749
Baubles: 1.12-1.5.2
JEI: 1.12.2-4.12.0.215
Thaumcraft: 1.12.2-6.1.BETA22
Thaumic Arcana: 0.1.1

Thanks for looking into it.

Best regards,
wamc

**Comment by Frontrider** [comment]
Thanks, looking into it.

**Comment by Frontrider** [comment]
Also, thanks for further making it sure, that it works.
