### ISSUE TITLE
[1.12.2] [0.1.1] Missing research entry descriptions

### ISSUE THREAD

**Issue by wamc2017** [Frontrider/thaumic_arcana#43]
Hi,

Advanced creature enchants (stage3) and plant growth (stage 5) are missing some description.
![advancedcreaturestage3](https://user-images.githubusercontent.com/33242447/44308453-870dbd00-a3b6-11e8-8ba2-288aafa6fd12.png)
![plantgrowthstage5](https://user-images.githubusercontent.com/33242447/44308455-8aa14400-a3b6-11e8-8ee6-37ad501f4820.png)

Mods used to test this issue (no other mods installed):
Forge:  14.23.4.2749
Baubles: 1.12-1.5.2
JEI: 1.12.2-4.12.0.215
Thaumcraft: 1.12.2-6.1.BETA22
Thaumic Arcana: 0.1.1

Thanks for looking into it.

Best regards,
wamc

**Comment by Frontrider** [comment]
Filled in the missing parts.
