### ISSUE TITLE
[1.12.2] [0.1.1] Arcane fertilizer not craftable during research

### ISSUE THREAD

**Issue by wamc2017** [Frontrider/thaumic_arcana#44]
Hi,

The alchemical fertilization research (stage 4) needs some arcane fertilizer, but at that point there's no recipe available for the fertilizer itself. It's also not craftable using the crucible until the research itself is completed (stage 5)

![arcanefertilizer](https://user-images.githubusercontent.com/33242447/44308498-63974200-a3b7-11e8-8292-c1651e54dd67.png)

Mods used to test this issue (no other mods installed):
Forge:  14.23.4.2749
Baubles: 1.12-1.5.2
JEI: 1.12.2-4.12.0.215
Thaumcraft: 1.12.2-6.1.BETA22
Thaumic Arcana: 0.1.1

Thanks for looking into it.

Best regards,
wamc

**Comment by Frontrider** [comment]
It should be.  Is it crafteable in earlier stages?

**Comment by wamc2017** [comment]
Nope.

**Comment by Frontrider** [comment]
This kind of stuff is hard to debug, since I can't revoke a single research.
I will apply a possible fix.

**Comment by enderger** [comment]
I think that whats happening is that, in my testing, only the max recipe shows. The other recipes never render.

**Comment by Frontrider** [comment]
I have to find that typo.

**Comment by Frontrider** [comment]
Also found a way to revokr a single research.

**Comment by Frontrider** [comment]
I think I found it, and I shoukd have expected it. All thise recipes require the same amount of essentia, but the resulting amount is increasing.

**Comment by Frontrider** [comment]
I'll rework the research, I guess the API doesn't allow what I'm trying to do.

**Comment by Frontrider** [comment]
Changed the research, now it's only one step.
Will be released this weekend.
