### ISSUE TITLE
Suggustion: Alchemical Paper

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#5]
Ok, so I find that paper runs out quite quickly in the research table. I suggest that we are given the ability to create paper(a crucible recipe that involves paper as the catalyst) that is able to be reused 10 times. This paper could be combined with 1 piece of leather (with an 8 to 1 ratio and 1 of each crystal) in an arcane workbench to produce an empty Arcane Journal. These journals can be opened like written books, but show a gui with slots for 64 arcane paper and a slot for the arcane paper that is in use. This can be infused with 6 pieces of thaumium and 2 pieces of arcane paper to create a thaumium-infused arcane journal that holds 128 arcane paper. I should mention that arcane paper uses vanilla durability and is not stackable in normal circumstances, that is what arcane journals are for. If you then use a more unstable infusion craft that requires 6 void metal and 2 arcane paper, you can get a void arcane journal that holds 256 arcane paper.

**Comment by Frontrider** [comment]
I don't think that it's possible to add a new item into the research table. What I think is just paper 
manufacturing. (with wood log as the catalyst)

Could be grouped together with other plant based products, in a similar fashion to hedge alchemy. 
I also have to figure that out, what else could be produced like this.

**Comment by enderger** [comment]
OK, I'll be watching for release 1!

**Comment by enderger** [comment]
Wood conversion comes to mind, as builders would probably want a way to cycle between wood types(oak logs and spruce planks are common for house building, so a spawn with a hot climate(biomes are pieced together based on temperature, so being unlucky with an overlarge hot heat map is possible)would make this recipe useful). Cactus wood could be another useful addition, especially for if you spawn in the middle of the desert and need wood.

**Comment by Frontrider** [comment]
Next release, and I have a way of "duplicating" wood. I also don't want to make you not to leave your base. Go out, and find those saplings. Be rewarded by the success of your adventure.

And that's a separate issue.

**Comment by enderger** [comment]
> 

Could be grouped together with other plant based products, in a similar fashion to hedge alchemy. I also have to figure that out, what else could be produced like this.
--
... is what I was giving some ideas for.

**Comment by Frontrider** [comment]
The current idea: partially reanimate plant based materials (mostly dye's) and then make them grow a little to make more of them.

**Comment by Frontrider** [comment]
I did had wood conversion as a concept in my head, I might do a variation on it, but I ended up discarding it.

**Comment by Frontrider** [comment]
In the meantime , I also developed the way I'm going to do it. Tc really gave me trouble, since as far as I see, it doesn't allows ore dictionary inputs. It will not be in the first release, but I'll do it shortly afterwards.

**Comment by Frontrider** [comment]
Included in the first release, my original idea did not, but the second taught did.

**Comment by enderger** [comment]
Which one made it into the mod?

**Comment by Frontrider** [comment]
Turn a log of wood into paper.
