### ISSUE TITLE
Breeding animals does not always work

### ISSUE THREAD

**Issue by mikeThePlayer** [Frontrider/thaumic_arcana#51]
So after a bit of testing with breeding animals (I tried only cows, pigs and sheeps), I found out that there is quite a big chance for them to not breed.

- I had 18 pairs of all 3 species (so 36 cows, 36 pigs...). After using appropriate food I got 5 new cows (5 of 18), 5 of 18 sheeps, and 2 of 18 pigs using carrots, and 4 of 18 pigs using potatoes.
- Without Thaumic Arcana installed, I got always 18 new babies for every type of animal.

Mods installed were only:
- Thaumcraft Beta 24
- Baubles
- Thaumic Arcana 0.2.1

Not sure if this "feature" is indended (with all the possible creature enchants like fertility...), but it felt like a bug to me. Hope I am not wrong.

Have a nice day, Mike.

**Comment by Frontrider** [comment]
Yeah that is not intended. I think I know what might be happening.

Theres a logic in there that allows to disable the extras, and also a chance disable the breeding itself. Should not be activated tough, unless the level of the enchant is "negative".

**Comment by Frontrider** [comment]
Did you had them enchanted, or just normally?

**Comment by Frontrider** [comment]
Than I know exactly what's going on.

**Comment by mikeThePlayer** [comment]
Awesome! :) looking forward for a fix

**Comment by Frontrider** [comment]
Fixed in dev, today or tomorrow is what I'm aiming for.

**Comment by Frontrider** [comment]
I have some issues in my developer enviroment (no mods load up) there will be no relese until I fixed that.

**Comment by wamc2017** [comment]
Are you using forge version  14.23.4.2759? It's flagged as buggy, had some issues earlier in a dev env with loading up dependencies as well, upgrading to 2760 fixed it...
