### ISSUE TITLE
Crash on startup with version 0.3.1

### ISSUE THREAD

**Issue by angelnc1989** [Frontrider/thaumic_arcana#53]
https://pastebin.com/B7JrcyJA

**Comment by mikeThePlayer** [comment]
Also crashes with only must have mods.

https://pastebin.com/TdVxpHWR

**Comment by Frontrider** [comment]
Fix will be there tomorrow (or tonight, it' 2pm here now). Did not happen when I was testing it, but I see what's going on.

**Comment by Frontrider** [comment]
Uploaded a new jar that should not have this issue.

**Comment by angelnc1989** [comment]
Where?

**Comment by Frontrider** [comment]
So it's fixed?

**Comment by angelnc1989** [comment]
> So it's fixed?

Yes =)
That's why I closed the issue.
