### ISSUE TITLE
[1.12] Crash on gamestart, The mod will not warn that forgelin must be installed.

### ISSUE THREAD

**Issue by MasterEnderman** [Frontrider/thaumic_arcana#56]
Thaumcraft: 6.1BETA24
Thaumic Arcana: 0.5.0
Forge: 14.23.4.2760
Crash: https://pastebin.com/j6QaXuAf

**Comment by Frontrider** [comment]
Which forgelin version?

**Comment by Frontrider** [comment]
I'll check if my dependencies are set correctly, it should have noted that you must have forgelin installed.

**Comment by MasterEnderman** [comment]
That's right i didn't have forgelin installed. Would be nice if the mod tells that, if it isn't present. :D sorry for stealing your time.

**Comment by Frontrider** [comment]
Gonna keep it open until I fixed it. It's a bug, forge has a system to handle it.
