### ISSUE TITLE
Crash when villagers make love

### ISSUE THREAD

**Issue by mikeThePlayer** [Frontrider/thaumic_arcana#57]
So pretty much what the title says. I made a simple villager farm (with 2 villagers) and when they start making their thing and baby should be born, the game crashes.

Villagers were spawned with egg in creative mode, but I also tested it with normally spawned villagers in survival mode (so there should be no enchants applied to them).

Tested with just a few important mods. Also everything works fine without Thaumic Arcana.

Crash report: https://pastebin.com/0i7keLE4

**Comment by Frontrider** [comment]
I see. gonna be an easy fix, thank you.

**Comment by Frontrider** [comment]
fixed, the enchant will only work on animals. Not going to figure it out for villagers right now, but thank's for giving that some attention.

**Comment by mikeThePlayer** [comment]
It was just a random accident when I was trying to get new villagers :D 
I am happy that I helped you.

**Comment by Frontrider** [comment]
Still thank you, since I did not anticipated that people would try to use it to breed villagers. Which is pretty reasonable. I'll have to add that "creatures with higher intellect are somewhat unaffected"
