### ISSUE TITLE
Crash with Charset lib

### ISSUE THREAD

**Issue by Voxel-Friend** [Frontrider/thaumic_arcana#59]
https://gist.github.com/Voxel-Friend/7ef72c2983e89e22553aaa1532a5cc70
Using:
Forge:14.23.5.2775
Baubles:1.5.2
Charset Lib:0.5.5.6
Shadowfacts' Forgelin:1.8.0
Thaumcraft:6.1.BETA26
Thaumcraft Research Loader:1.0
Thaumic Arcana:1.0

**Comment by Sunconure11** [comment]
Can confirm the same issue.

https://paste.dimdev.org/gukiqifuke.mccrash

**Comment by Voxel-Friend** [comment]
Got enough mods there? o.o"

**Comment by Frontrider** [comment]
I see, I'll roll out a fix today.

**Comment by Frontrider** [comment]
fixed.
