### ISSUE TITLE
Obtaining/using the pre release

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#6]
How can I use pre-release 1 of this mod? I would like to beta test the mod, but I can't figure out how to use the decompiled code in eclipse to get myself a testing jar. I will not release it to the public myself, I just want to test for bugs outside of the development environment.

**Comment by enderger** [comment]
Unfortunately, this mod seems to be impossible to compile due to the usage of depreciated gradle features. 

Stacktrace: https://gist.github.com/enderger/6a212a2a0ddef047a1be9f761e375747

**Comment by Frontrider** [comment]
Blame forge, I made no modifications to the defaults, and haven't ran the build task yet. (yesterday it took too long)

And Use intellij instead of eclipse, importing the gradle project works out of the box.

**Comment by enderger** [comment]
I ran the gradle build task
I was compiling from the command line
and I'll look into trying intellij if it works on linux.

**Comment by Frontrider** [comment]
I have no idea how people use eclipse with gradle (I have a general idea about using eclipse in general, but intellij still looks objectively better to me), it's a real pain in the back.

**Comment by Frontrider** [comment]
That is the combo I use to develop it.

**Comment by Frontrider** [comment]
The balance is also something I have to check, the protection 3 enchantment made me invulnerable from certain mobs.

**Comment by enderger** [comment]
I'll be sure to test that
And gradle is not eclipse: it's the linux gradlew

**Comment by enderger** [comment]
Installing it from the arch user repository (on linux, we usually stick to official repositories for our distro and install what isn't there from the internet)

**Comment by Frontrider** [comment]
Gradlew is the gradle wrapper (NOT any other gradle that you installed on your computer) that forge includes in the project. Only exists in the project.

With intellij: file, open, select build.gradle, and switch to gradle wrapper configuration. 
From that point it will work out of the box, and will probably ask you to install the mcdev plugin. (support for forge, bukkit, sponge etc.)

**Comment by enderger** [comment]
Odd, I have to type in gradle setupDecompWorkspace when I want to begin coding, gradlew fails

**Comment by enderger** [comment]
The thaumcraft api seems to not be properly annotated. I may need to comment out some of the lines within the api.

**Comment by enderger** [comment]
Where does intellj output it's compiled jars?

**Comment by Frontrider** [comment]
Most of it relies on thaumcraft's api, so recipes need no testing. (there's one that is broken, and I have to figure why)
Last time I checked, the plant balls worked as expected, the nutrient mix worked as expected, enchanting worked as expected.

The enchantment balance is something that needs to be tested.

**Comment by Frontrider** [comment]
calling it done and closed.
