### ISSUE TITLE
TA making Mekanism crash on server start

### ISSUE THREAD

**Issue by minakitty** [Frontrider/thaumic_arcana#60]
Trying to install Thaumic Arcana for the first time, but it's causing Mekanism to crash the server on start.  Removing the mod fixes the problem, but of course that's not idea.  It seems this line is the most likely cause of the problem:

`java.lang.IllegalArgumentException: Parameter specified as non-null is null: method hu.frontrider.arcana.InfuseSlimiumTool.func_77569_a, parameter worldIn`

[crash-2018-11-21_15.44.36-server.txt](https://github.com/Frontrider/thaumic_arcana/files/2606167/crash-2018-11-21_15.44.36-server.txt)

**Comment by Frontrider** [comment]
Fixed as of 1.1.0
