### ISSUE TITLE
New crash with FTBUtilities

### ISSUE THREAD

**Issue by minakitty** [Frontrider/thaumic_arcana#61]
Thaumic Arcana v1.1
FTBLib 5.1.3.30
FTB Utilities 5.3.0.54

Not sure the cause this time unfortunately
[crash-2018-11-21_19.15.51-server.txt](https://github.com/Frontrider/thaumic_arcana/files/2606487/crash-2018-11-21_19.15.51-server.txt)

**Comment by Frontrider** [comment]
Completly on me FTBLib is not to blame, and I have no idea how that went over my head.

**Comment by Sunconure11** [comment]
https://pastebin.com/KKcuFeU5

Encountering the issue too.

**Comment by Frontrider** [comment]
Having some problems that are currently preventing me from building. Trying to resolve it as quickly as possible.

**Comment by Frontrider** [comment]
This class ` net.minecraft.client.resources.I18n` exist only on the client, and I definitely call it on a server, and that is a huge problem.

Sorry for being late with it I've been busy+I'm having issues in my devenv that I'm resolving.

**Comment by minakitty** [comment]
Luckily in my case this was a new mod, so I just have it disabled in the
meantime

**Comment by Frontrider** [comment]
Is it still a thing?

**Comment by Sunconure11** [comment]
No, it is not a thing anymore.

**Comment by minakitty** [comment]
Meaning that the current version should work?

**Comment by Frontrider** [comment]
If I managed to fix it than I'm closing it. :)
