### ISSUE TITLE
Mounts cannot move and cause DC

### ISSUE THREAD

**Issue by schindlershadow** [Frontrider/thaumic_arcana#64]
Having thaumic_arcana installed causes issues with other mod's mounts, namely they cannot move or cause a DC:
 [INFO] SchindlerShadow lost connection: Invalid move vehicle packet received

Related issue: https://github.com/ProjectKorra/AvatarMod/issues/100

Thaumic+Arcana-1.1.1
FML: MCP 9.42 Powered by Forge 14.23.5.2784 Optifine OptiFine_1.12.2_HD_U_C7 110 mods loaded, 110 mods active

**Comment by Frontrider** [comment]
Can I get some actual data? If it was really only me, than no entities should move.

**Comment by FavouriteDragon** [comment]
Yeah you need to provide the server log.
That way I can fix it it's a problem on my end.

**Comment by Frontrider** [comment]
Thank you, that is enough for me.
