### ISSUE TITLE
Research table card bug

### ISSUE THREAD

**Issue by ChisenDrakorus** [Frontrider/thaumic_arcana#66]
Any and all biomancy research that involves phials of essentia will not complete. They cannot be clicked, even with everything in inventory.

Thaumcraft B26, TA v1.0.0 because of a crash in later versions I will post separately.

**Comment by ChisenDrakorus** [comment]
Well, its still a bug, but I found out the problem is it says a phial of aqua when it wants an empty phials.

**Comment by Frontrider** [comment]
Replaced the phial with shards, that are acquired in a cleaner fashion.
