### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by ChisenDrakorus** [Frontrider/thaumic_arcana#67]
Either version above 1.0.0 crashes upon loading even brand new worlds. 
Crash log bellow:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  HCASM (HammerCore-1.12.2-2.0.3.5.jar)
  ForgelinPlugin (Forgelin-1.8.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  LoadingPlugin ([1.12]+VersionChecker-1.3.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 11/26/18 11:50 AM
Description: Loading entity NBT

kotlin.TypeCastException: null cannot be cast to non-null type net.minecraft.nbt.NBTTagCompound
	at hu.frontrider.arcana.capabilities.scar.ScarredStorage.readNBT(ScarredStorage.kt:15)
	at hu.frontrider.arcana.capabilities.scar.ScarredStorage.readNBT(ScarredStorage.kt:9)
	at hu.frontrider.arcana.capabilities.scar.ScarProvider.deserializeNBT(ScarProvider.kt:25)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:135)
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1852)
	at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:318)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:116)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at hu.frontrider.arcana.capabilities.scar.ScarredStorage.readNBT(ScarredStorage.kt:15)
	at hu.frontrider.arcana.capabilities.scar.ScarredStorage.readNBT(ScarredStorage.kt:9)
	at hu.frontrider.arcana.capabilities.scar.ScarProvider.deserializeNBT(ScarProvider.kt:25)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:135)

-- Entity being loaded --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 393
	Entity Name: Niwashi
	Entity's Exact location: -374.20, 64.00, 279.13
	Entity's Block location: World: (-375,64,279), Chunk: (at 9,4,7 in -24,17; contains blocks -384,0,272 to -369,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1852)
	at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:318)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:116)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@46b812dc
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 961087744 bytes (916 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version           | Source                                        | Signature                                |
	|:--------- |:------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                      | 9.42              | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | versionchecker           | 1.3.0             | [1.12]+VersionChecker-1.3.0.jar               | None                                     |
	| UCHIJAAAA | baubles                  | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | biomesoplenty            | 7.0.1.2399        | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
	| UCHIJAAAA | rustic                   | 1.0.12            | rustic-1.0.12.jar                             | None                                     |
	| UCHIJAAAA | forgelin                 | 1.8.0             | Forgelin-1.8.0.jar                            | None                                     |
	| UCHIJAAAA | thaumcraft               | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| UCHIJAAAA | thaumcraftresearchloader | 1.0               | thaumcraftresearchloader-1.0.jar              | None                                     |
	| UCHIJAAAA | thaumic_arcana           | 0.6.0             | Thaumic+Arcana-1.1.0.jar                      | None                                     |
	| UCHIJAAAA | jei                      | 4.13.1.222        | jei_1.12.2-4.13.1.222.jar                     | None                                     |
	| UCHIJAAAA | immersiveengineering     | 0.12-86           | ImmersiveEngineering-0.12-86.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | clochecall               | 1.1.1             | ClocheCall-1.1.1.jar                          | None                                     |
	| UCHIJAAAA | clumps                   | 3.1.1             | Clumps-3.1.1.jar                              | None                                     |
	| UCHIJAAAA | cyclopscore              | 0.11.11           | CyclopsCore-1.12.2-0.11.11.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | colossalchests           | 1.6.11            | ColossalChests-1.12.2-1.6.11.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | cookingforblockheads     | 6.4.65            | CookingForBlockheads_1.12.2-6.4.65.jar        | None                                     |
	| UCHIJAAAA | ctm                      | MC1.12.2-0.3.2.20 | CTM-MC1.12.2-0.3.2.20.jar                     | None                                     |
	| UCHIJAAAA | engineeredgolems         | 1.0               | Engineered+Golems-1.0.jar                     | None                                     |
	| UCHIJAAAA | engineersdoors           | 0.8.0             | engineers_doors-1.12.2-0.8.0.jar              | None                                     |
	| UCHIJAAAA | ea                       | 1.0.1             | ExpandedArcanum-1.0.1.jar                     | None                                     |
	| UCHIJAAAA | familiarfauna            | 1.0.10            | FamiliarFauna-1.12.2-1.0.10.jar               | None                                     |
	| UCHIJAAAA | hammercore               | 2.0.3.5           | HammerCore-1.12.2-2.0.3.5.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | waila                    | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| UCHIJAAAA | immersivepetroleum       | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar           | None                                     |
	| UCHIJAAAA | immersivetech            | 1.3.10            | immersivetech-1.12-1.3.10.jar                 | None                                     |
	| UCHIJAAAA | harvestcraft             | 1.12.2z           | Pam's+HarvestCraft+1.12.2za.jar               | None                                     |
	| UCHIJAAAA | jehc                     | 1.12.2            | JEHC-1.12.2-1.6.2.0.jar                       | None                                     |
	| UCHIJAAAA | journeymap               | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | naturescompass           | 1.5.1             | NaturesCompass-1.12.2-1.5.1.jar               | None                                     |
	| UCHIJAAAA | reborncore               | 3.10.4.348        | RebornCore-1.12.2-3.10.4.348-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | rusticthaumaturgy        | 1.0               | Rustic+Thaumaturgy-2.7.jar                    | None                                     |
	| UCHIJAAAA | rusticbopwoods           | 1.0               | rusticbopwoods-1.0.jar                        | None                                     |
	| UCHIJAAAA | cardboardboxes           | 0.0.2.7           | SBM-CardboardBoxes-1.12.2-0.0.2b7.jar         | None                                     |
	| UCHIJAAAA | stevescarts              | 2.4.24.118        | StevesCarts-1.12.2-2.4.24.118.jar             | None                                     |
	| UCHIJAAAA | thaumadditions           | 10r               | ThaumicAdditions-1.12.2-10r.jar               | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | tcinventoryscan          | 2.0.10            | ThaumicInventoryScanning_1.12.2-2.0.10.jar    | None                                     |
	| UCHIJAAAA | thaumicjei               | 1.2.1             | ThaumicJEI-1.12.2-1.5.5-23.jar                | None                                     |
	| UCHIJAAAA | tombmanygraves           | 1.12-4.2.0        | TombManyGraves-1.12-4.2.0.jar                 | None                                     |
	| UCHIJAAAA | tombmanygraves2api       | 1.12.2-1.0.0      | tombmanygraves2api-1.12.2-1.0.0.jar           | None                                     |
	| UCHIJAAAA | wawla                    | 2.5.264           | Wawla-1.12.2-2.5.264.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | waystones                | 4.0.67            | Waystones_1.12.2-4.0.67.jar                   | None                                     |
	| UCHIJAAAA | weirdinggadget           | 1.0               | weirdinggadget-1.12.2-2.0.5-universal.jar     | None                                     |

	Loaded coremods (and transformers): 
HCASM (HammerCore-1.12.2-2.0.3.5.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
ForgelinPlugin (Forgelin-1.8.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin ([1.12]+VersionChecker-1.3.0.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 1499 names; 2253 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Failed!
Dependent Mods:
    -Thaumic Additions: Reconstructed (thaumadditions) @10r

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.10.4.348
		Runtime Debofucsation 1
		RenderEngine: 0
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Frontrider** [comment]
Gonna be an easy fix.

**Comment by Frontrider** [comment]
Fixed, releasing it today or tomorrow.

**Comment by ate0ate** [comment]
I'm getting a similar crash and was wondering if this fix is supposed to be in version 1.2.0 on curseforge or currently unreleased?

**Comment by Frontrider** [comment]
It's supposed to be in the release. Open a new issue with the crash report
