### ISSUE TITLE
Missing textures/language keys.

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#7]
Ok, so I know that issues should be 1 per thread, but I think that it would be easier for both of us if I send bug reports to you as I test since you probably would not want to scroll through issues as I report them. I feel that that would get confusing quickly. 

With that out of the way, I have found 2 missing textures(Raw Relief and Plant Balls) and 1 missing name(item.plant_ball.name).

I will revise the lang file again with my findings. A few researches have unlocalised names. I will edit my fork to fix these issues and make a new pull request.

**Comment by Frontrider** [comment]
I know about the missing textures, I'll have to make them.

Raw relief was an item that i intended to use for a potion, but I ended up using warp ward for the task.

**Comment by enderger** [comment]
Also, when I edited the lang file, I found that the tree research was not existent at all, nor is there anywhere that tells users how to perform creature enchantments. There is also still no research for the self-enchantment

**Comment by enderger** [comment]
The recipe tabs for the creature enchantment research are very messed up.

**Comment by Frontrider** [comment]
No proper internet for a few days, I'll notewhen it's fixed in dev.

**Comment by Frontrider** [comment]
fixed in dev:
- plantball has a texture and a name
- plantball has proper lore (lists the items that it contains)
- raw relief removed
- self/creature enchantment describes the application process.
- added leather production

current todo:
- tree research (PLANT_GROWTH_ADVANCED is the research key, I'll change the language keys accordingly)
- finalize the self enchantment application process.

What do you mean by messed up?

**Comment by Frontrider** [comment]
I'll also have to figure out a way to modularize my code in a way, that I can some unit testing (now that I know what I'm doing).

**Comment by enderger** [comment]
By messed up, I mean that the recipe for each book shows the recipe for the book above it when you click on it. By the way, if the milestone is what I think it is, I believe this should be closer to 0.5 because of the bugs being found before the jar was officially released by you.

**Comment by enderger** [comment]
I can send you my jar if you want. We would have to get a private connection to prevent leaks from happening due to credit issues.

**Comment by enderger** [comment]
I can confirm that the majority of popular thaumcraft addons work without issue with this addon.

**Comment by Frontrider** [comment]
I expected that, since I don't do any hacking. I only interact with thaumcraft via it's API, the rest is strictly what forge provides.

**Comment by enderger** [comment]
I will send a link to a short video showing the recipie bug.

**Comment by Frontrider** [comment]
Do it, last time I checked it looked fine. I know that there is an insane recipe for the strength book, since that is like 3 enchantments in one.
 * strengthen the muscles
 * strengthen the bones and tendrils (MHA, Izuku Midoria is the reference, we don't want that, although,if I think about it, it would actually be interesting. "Super strength that destroys your body")
 * improve the vitals so it can support it. 

Might remove the research, and think about it.

**Comment by enderger** [comment]
Did you look in the recipies shown in the thaumonomicon? The fertility enchant should not show anything when you click on it, but the book below it will show its recipe.

**Comment by Frontrider** [comment]
The recipe for the "empty" enchanted book is broken, if that is what you mean.

**Comment by enderger** [comment]
No, and unless you’ve updated the mod files themselves since I made my jar file, the bug still exists.

**Comment by enderger** [comment]
Another possibility is a discrepancy between the deobf and compiled code.

**Comment by enderger** [comment]
I can’t test the features that are not on GitHub yet, so it may have been fixed already.

**Comment by Frontrider** [comment]
In the book, all recipes shifted downwards by one, and they require the wrong book (it's supposed to be the one before it) to be crafted with.

**Comment by enderger** [comment]
That's the one!

**Comment by Frontrider** [comment]
And a general rule of thumb: The description "something is wrong" is never enough, describe the entire problem, with as many details as possible.

**Comment by Frontrider** [comment]
Also different issue :P, but I'm too lazy to move everything  there  #16

**Comment by enderger** [comment]
I had trouble wording the issue

**Comment by Frontrider** [comment]
The original is fixed, closing it and calling it done.
