### ISSUE TITLE
A weird bug: keep losing half a heart

### ISSUE THREAD

**Issue by L1ttleFlyyy** [Frontrider/thaumic_arcana#75]
My friends and I am playing on our custom modpack including Thaumic Arcana(TA). 
A weird issue is, after we unlock some research in TA, when attacked by mobs, there is a chance that our characters get into a 9.5-heart max health state. i.e. as soon as we recover to 10 heart, we will start being hit by an invisible force until our health is below 9.5 heart.
Looks like, this invisible force/debuff is trying to keep us at 9.5 heart, really annoying.

We have done a lot of tests and verified this bug lies in one of the TA research. As long as we delete TA or start a new Game without unlock any TA research, this bug won't happen.

Minecraft version: 1.12.2
Thaumic Arcana 1.2.0
ThaumCraft 6, beta 26
Other mods in mod pack: IC2, advanced solar panel and some other utilities like JEI, Journey Map, wala, etc.

A simple way to reproduce this bug is:
1. Start a new game, allow cheating
2. Unlock all research using /tc research USERNAME all
3. Get a suit of Quantum Suite from IC2 to protect you from losing health. Enchanted diamond armors are also good
4. Summon a Wither Skeleton and let it attack you freely. (The chance increases greatly when facing DoT like wither/fire/poison)
5. Wait for several minutes.

Typically, within 2 minutes, your character will get this 9.5-heart debuff.

**Comment by Frontrider** [comment]
I'll be honest, I got bored/burnt out on it once and I stopped maintaining it.

The code is completely free to use if you find someone who can fix it go for it. (I'm more than willing to give permissions for the assets.)

**Comment by L1ttleFlyyy** [comment]
I understand. 
Thanks for presenting us this fantastic mod. Good luck with your life~

**Comment by Frontrider** [comment]
Yeah, that was meant to be a thing.

Original intention:
One research wounds you (lab accident), then you have to walk through a path to get yourself healed. If you ignore it will keep hurting you.

I'm not touching this code (I'm also a little sick of it), but if you make a pr with a fix, then I can try to push a release it at most a week, depending on how much time I have. If you don't want to wait for it, make a fork and I can give access to the project site.

**Comment by Frontrider** [comment]
Sometime next week I'll remove the issues tab so I won't get any of these emails. Sorry.

**Comment by AgentA1cr** [comment]
I may take a look at it, but, while I have a basic understanding of java, I'm not super familiar with the technical side of Minecraft modding. I'll see what I can do. Which researches were supposed to do which thing?

**Comment by Frontrider** [comment]
It's not that bad actually. 

To be honest, I have no idea.

**Comment by AgentA1cr** [comment]
So, for now, probably just disable the scar mechanic?
