### ISSUE TITLE
Feedback on the research cards

### ISSUE THREAD

**Issue by Frontrider** [Frontrider/thaumic_arcana#8]
Put down  stone table, a melon or a pumpkin next to the research table.

I'd like some feedback on that. (the formatting is wrong in some places, I haven't checked if fixed in dev)

**Comment by enderger** [comment]
For starters, you can't exactly dissect a living animal.

**Comment by Frontrider** [comment]
Have you actually checked the required items? :P

**Comment by enderger** [comment]
There are 2 different cards with dissect in the name within the lang file

**Comment by enderger** [comment]
I’ll check the cards, but I think that I realized what the items may be. Might I suggust a word change from dissect the dead to dissect the undead?

**Comment by Frontrider** [comment]
Those items can come for simply dead sources, not only undead. Eg: bones and rotten flesh from tombs.
That is my reasoning.

**Comment by Frontrider** [comment]
I hope that answers the reasoning.

**Comment by enderger** [comment]
Dissect remains may fill the purpose, then

**Comment by enderger** [comment]
I say that because both imply the creature to be dead

**Comment by enderger** [comment]
Both cards, that is

**Comment by Frontrider** [comment]
Dissect remains it is.

**Comment by Frontrider** [comment]
If that's all, than I'm closing it.

**Comment by Frontrider** [comment]
The research aid, is going to be changed, into the new "Experiment Table". For now, you can check the model in the "showcase" channel of the MMD discord.

**Comment by Frontrider** [comment]
Going to call it done.
