### ISSUE TITLE
I cannot complete Hedge Alchemy

### ISSUE THREAD

**Issue by Browmy** [Frontrider/thaumic_arcana#81]
The crucible recipe for the cobweb doesn't show. I tried to look in internet for the recipe but the way that it is supposed to work didn't help me at all. Is there a way to fix it, give me the research throught commands? or just give me how it is supposed to be crafted and I can try it out.

**Comment by enderger** [comment]
I do believe that any crafting recipe for cobwebs should count, try using the recipe from Botania if you have it.

**Comment by Browmy** [comment]
I thought that you are supposed to craft it using the crucible, I will try it later.

**Comment by enderger** [comment]
Last I played it, Thaumcraft never actually checks which recipe is used. I’ve experienced this by crafting slime blocks back into slime.

**Comment by Browmy** [comment]
It worked!! Thank you.
